---
title: "STAT5574 Report"
author: "Alexander Durbin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
geometry: margin = 1in
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summit Consulting Introduction

Summit Consulting is a statistical consulting firm founded in 2003 by Dr. Albert Lee. Dr. Lee's specializations in sampling techniques and econometric modeling prepared him for pursuing a career as a senior consultant at Bates White. As senior consultant, Dr. Lee was a critical component in Bates White's largest cases, the vitamin antitrust litigation and W.R. Grace asbestos litigation. After being exposed to litigation, Dr. Lee began broadened his focus from consulting statistician to also statistical expert witness. Located in Washington, D.C., Dr. Lee believed that his background in economics, sampling techniques, and litigation preparation would best serve governmental clients. Thus, being in walking distance the Department of Labor, Federal Housing Financing Agency, and other governmental agencies has been a priority since.

One of Summit's first clients was the Office of Management and Budget. Here Dr. Lee assisted then-credit policy analyst Anthony Curcio on credit subsidy model development. Working closely toegther, Dr. Lee identified Mr. Curcio's experience in needing to outsource statistical work, coupled with his background in federal credit modeling and advanced knowledge of federal budgets as an asset and possible ally of Summit Consulting. Dr. Lee gained a wealth of knowledge from Mr. Curcio on further opportunities for government contracts, other consulting opportunities, and preparing to be an expert witness. Their mutual interests in economics and consulting work formed a powerful working relationship; Mr. Curcio joined Summit Consulting as its second employee, additional founding member, and second principal in 2003.

Hereafter, Dr. Lee led a small team of economists and statisticians working on short-term government consulting contracts sourced by Mr. Curcio. However, Dr. Lee sought additional consistent long-term projects. He cultivated his client relationships with the Department of Labor and was able to source a long-term contract with the agency. They have been Summit's longest client and are often prioritized. Additionally, Summit established a group of employees that work on-site fulltime. This team primarily works onsite with regular offfice hours to always be available to the Department of Labor.  

While Summit was consistently growing and maintaininig its focus as a governmental contractor, Dr. Lee was not satisfied with the lack of opportunities as a statistical expert witness. These opportunities presented themselves during the United States Housing Bubble burst in 2006. Summit consulting was then hired on the behalf of law firm Quinn Emanuel, as well as Freddie Mac and CoreLogic, to construct Automated Valuation Models with the goal of possibly pursuing legal action against financial institutions that provided the majority of residential loans and residential home appraisals. Dr. Lee then researched how to idenfiy predatory residential mortgage backed securities. These predatory loans were quantified as those with significant appraisal inflation. Working with other economic experts, Dr. Lee successfully derived regression models that predict appraisal inflation and has since been used as a statistical expert witness in many cases to discuss their validity.

<!-- This paragraph needs to discuss the jump from this initial work to what summit is doing today. things like trials taking years to get underway, massive hiring, expanding of departments, core litigation team, and further investors joining the company. That should be a very sufficient introductory section on summit. dont really say anything about the workplace or technology, i think that technology can have its own section in this paper. just say how the work was leveraged into further long term contracts and dr lee was able to establish himself as an export witness with shane thompson further following him. so this paragraph need not be long just a time jump from 2007-2016 and how trials take years to complete, we furtther focusing on expanding into other litigations. -->

This abundance in litigation work has thus been a core focus of Summit with the majority of cases taking years of analytical and legal work before completetion. Dr. Lee writes multiple reports on his regression models and defends them in court before the opposition's expert witness gives his rebuttle report. Summit then has on average two weeks to provide their own rebuttle report and any other analytics they feel necessary to clarrify. After Dr. Lee provides his reports and testimony, it can take months before the trial is back in session or concluded.

In between trials, Dr. Lee and Mr. Curcio have sought to further grow Summit's client base while also adhearing to its core focuses. Summit has expanded to multiple departments with different expertise. In addition to the litigation directorate, other departments include federal credit modeling and forecasting and applied statistics and economics. These groups adhere not only to Summit's vision but most importantly to its founding principals' education and professional experiences. Summit has also partnered with multiple academic institutions to cultivate a working group of associate subject matter experts in addition to opportunities to become expert witnesses.

